name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: tshirts fail
      run: |
        gcc -Wall -Wextra -Werror tshirts.c tshirts-test.c -o tshirts.out

    - name: misaligned fail
      run: |
        gcc -Wall -Wextra -Werror misaligned.c misaligned-test.c -o misaligned.out

    - name: alerter fail
      run: |
        gcc -Wall -Wextra -Werror alerter.c alerter-test.c -o alerter.out
